services:
  postgres:
    image: postgres:16-alpine
    container_name: desstudy-pg
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: desstudy
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d desstudy"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
    external: true
    name: 0e06dd953c81974dbc238d548485e9a5d165d2fb9c29fd3ed030f5b35016f853
