// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/achievements" | "/admin" | "/admin/lessons/[id]" | "/admin/results" | "/assessment" | "/dashboard" | "/design-system" | "/learn" | "/learn/[slug]" | "/library" | "/mentor" | "/settings"
type AppRouteHandlerRoutes = "/api/admin/critique-analyze" | "/api/admin/enroll" | "/api/admin/lessons" | "/api/admin/lessons/[id]" | "/api/admin/lessons/[id]/blocks" | "/api/admin/lessons/[id]/blocks/[blockId]" | "/api/admin/lessons/[id]/publish" | "/api/admin/upload" | "/api/ai-review" | "/api/assessment" | "/api/attempt" | "/api/critique-fix" | "/api/observe-review" | "/api/upload"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/achievements": {}
  "/admin": {}
  "/admin/lessons/[id]": { "id": string; }
  "/admin/results": {}
  "/api/admin/critique-analyze": {}
  "/api/admin/enroll": {}
  "/api/admin/lessons": {}
  "/api/admin/lessons/[id]": { "id": string; }
  "/api/admin/lessons/[id]/blocks": { "id": string; }
  "/api/admin/lessons/[id]/blocks/[blockId]": { "id": string; "blockId": string; }
  "/api/admin/lessons/[id]/publish": { "id": string; }
  "/api/admin/upload": {}
  "/api/ai-review": {}
  "/api/assessment": {}
  "/api/attempt": {}
  "/api/critique-fix": {}
  "/api/observe-review": {}
  "/api/upload": {}
  "/assessment": {}
  "/dashboard": {}
  "/design-system": {}
  "/learn": {}
  "/learn/[slug]": { "slug": string; }
  "/library": {}
  "/mentor": {}
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
