// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/achievements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/achievements">> = Specific
  const handler = {} as typeof import("../../src/app/achievements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/lessons/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/lessons/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/lessons/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/results">> = Specific
  const handler = {} as typeof import("../../src/app/admin/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment">> = Specific
  const handler = {} as typeof import("../../src/app/assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/learn/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn">> = Specific
  const handler = {} as typeof import("../../src/app/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library">> = Specific
  const handler = {} as typeof import("../../src/app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mentor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentor">> = Specific
  const handler = {} as typeof import("../../src/app/mentor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/critique-analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/critique-analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/critique-analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/enroll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/enroll">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/enroll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lessons/[id]/blocks/[blockId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lessons/[id]/blocks/[blockId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lessons/[id]/blocks/[blockId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lessons/[id]/blocks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lessons/[id]/blocks">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lessons/[id]/blocks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lessons/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lessons/[id]/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lessons/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lessons/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lessons/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lessons/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lessons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lessons">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lessons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-review">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attempt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attempt">> = Specific
  const handler = {} as typeof import("../../src/app/api/attempt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/critique-fix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/critique-fix">> = Specific
  const handler = {} as typeof import("../../src/app/api/critique-fix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/observe-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observe-review">> = Specific
  const handler = {} as typeof import("../../src/app/api/observe-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
